### ISSUE TITLE
Emby: hardware detection in unprivileged container fails. 

### ISSUE THREAD

**Issue by scyto** [strongtz/i915-sriov-dkms#116]
I have HW transcoding with plex working just fine in plex - when i watch a stream the dashboard says transcoding (hw).
vainfo works just fine
groups look fine when i do `ls -la /dev/dri`

Emby seems to get really confused as it sees all 7 VFs instead of the actual single card0 / renderD128 in the guest /dev/dri path

How i have setup the container https://gist.github.com/scyto/e4e3de35ee23fdb4ae5d5a3b85c16ed3#file-vgpu-container-privileged-md

Emby errors attached

[hardware_detection-63832236107.txt](https://github.com/strongtz/i915-sriov-dkms/files/12836243/hardware_detection-63832236107.txt)

**Comment by opticblu** [comment]
SR-IOV is for VMs, not containers 

Containers can just use the host’s device directly IF permissions are in place.

You’re seeing 7 devices because it’s a container. A container behaves (for the sake of this explanation) more like an app with another OS inside rather than an entire VM. Hence privileged vs unprivileged. A VM has its own separate root/admin privileges. Hardware doesn’t need to be virtualized for a container.
