### ISSUE TITLE
 i915 module verification failed

### ISSUE THREAD

**Issue by GrampusV** [strongtz/i915-sriov-dkms#189]
After installing i915 on guest VM Ubuntu 22.04. Received a message.

> root@user-Standard-PC-Q35-ICH9-2009:~/i915-sriov-dkms# dmesg | grep i915
> [    2.948494] i915: loading out-of-tree module taints kernel.
> [    2.948522] i915: module verification failed: signature and/or required key missing - tainting kernel
> [    3.128038] i915 0000:01:00.0: Running in SR-IOV VF mode
> [    3.128142] i915 0000:01:00.0: [drm] *ERROR* GuC submission disabled
> [    3.188568] i915 0000:01:00.0: Device initialization failed (-19)
> [    3.189999] i915 0000:01:00.0: Please file a bug on drm/i915; see https://gitlab.freedesktop.org/drm/intel/-/wikis/How-to-file-i915-bugs for details.

Settings for /etc/default/grub

> GRUB_DEFAULT=0
> GRUB_TIMEOUT_STYLE=hidden
> GRUB_TIMEOUT=0
> GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
> GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i915.enable_guc=3"
> GRUB_CMDLINE_LINUX=""

kernel - 6.5.0-45-generic

**Comment by pasbec** [comment]
Are you using SecureBoot? What is the putput of `mokutil --sb-state`. If SecureBoot is enabled you need to import the dkms machine owner key (MOK) via `mokutil --import ${path_to_mok}`, choose some password, reboot, accept to import the key, enter the same password again and then it should work. Not sure where Ubuntu stores the dkms mok key and if SecureBoot is really the problem here.
